# SPDX-FileCopyrightText: Copyright (c) 2011-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

# Jakarta XML Binding (JAXB) 4.x reference implementation
jakarta.xml.bind.context.factory=org.glassfish.jaxb.runtime.v2.JAXBContextFactory
